# 使用packer构建镜像、部署测试环境  https://ci-cd.myscrm.cn/doc/#/gitlab-ci
stages:
  - test
  - deploy

.testTpl:
  image: satantime/puppeteer-node:14
  stage: test
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^dev/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(f|bg)-/'
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

test:
  extends: .testTpl
  script:
    - 'yarn'
    - 'yarn test:ci'
    - 'yarn test:e2e:ci'
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
      junit:
        - junit.xml
        - je2e.xml
    paths:
      - coverage

pages:
  extends: .testTpl
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
